### ISSUE TITLE
Common Voice

### ISSUE THREAD

**Issue by couci** [mozilla/CampaignsforMDM#14]
## Strategy Docs
* [Executive Brief](https://docs.google.com/document/d/1bUlmggzxI9wW6OHde5o3teKjQgczySCqAuw5Ur3zwnI/edit)
* [Comms Copy](https://docs.google.com/document/d/1yfzdO2PojYhoOzBU_8SR-RMhgigSe3oodqIE_xvuA5U/edit#)  

## Major Dates & CTAs
- [x] April 16 - Awareness Email
- [ ]  April 20th - Recruit for site hosts & Reviewers
- [ ] April 30th - Reminder
- [ ] May  7 - Reminder
- [ ] May - 9 - Tomorrow
- [ ] May 10 - Do it 
- [ ] May 12- Thank you & Results
